    $( function() {
    const stateSelect = document.getElementById('state');
    states.forEach(function(state) {
        const option = document.createElement('option');
        option.value = state.abbreviation;
        option.text = state.name;
        stateSelect.appendChild(option);
    });

    $( "#department" ).selectmenu();
    $( "#state" ).selectmenu();

    $('#date-of-birth').datetimepicker({
        timepicker: false,
        format: 'm/d/Y'
    });
    $('#start-date').datetimepicker({
        timepicker: false,
        format: 'm/d/Y'
    });
});

function saveEmployee() {
    const firstName = document.getElementById('first-name');
    const lastName = document.getElementById('last-name');
    const dateOfBirth = document.getElementById('date-of-birth');
    const startDate = document.getElementById('start-date');
    const department = document.getElementById('department');
    const street = document.getElementById('street');
    const city = document.getElementById('city');
    const state = document.getElementById('state');
    const zipCode = document.getElementById('zip-code');

    const employees = JSON.parse(localStorage.getItem('employees')) || [];
    const employeesData = [
        {
            firstName: 'Jordan',
            lastName: 'Walker',
            dateOfBirth: '07/06/2021',
            street: 'Ap #401-8093 Lacinia. St.',
            city: 'Nizhyn',
            state: 'Il',
            zipCode: '20555',
            department: 'Finances',
            startDate: '09/15/2022',
        },
        {
            firstName: 'Cole',
            lastName: 'Winters',
            dateOfBirth: '06/08/2022',
            street: 'P.O. Box 158, 2547 Euismod Av.',
            city: 'Chihuahua',
            state: 'KT',
            zipCode: '39289',
            department: 'Research and Development',
            startDate: '08/07/2022',
        },
        {
            firstName: 'Courtney',
            lastName: 'Green',
            dateOfBirth: '02/10/2023',
            street: '9770 Lorem Avenue',
            city: 'Kapiti',
            state: 'MI',
            zipCode: '42641',
            department: 'Public Relations',
            startDate: '10/25/2022',
        },
        {
            firstName: 'Cody',
            lastName: 'Dorsey',
            dateOfBirth: '04/01/2022',
            street: '613-1370 Cursus Rd.',
            city: 'Yên Thịnh',
            state: 'MO',
            zipCode: '68081',
            department: 'Customer Service',
            startDate: '09/28/2021',
        },
        {
            firstName: 'Dominic',
            lastName: 'Kline',
            dateOfBirth: '08/20/2021',
            street: '261-2182 Eget Street',
            city: 'Konya',
            state: 'VI',
            zipCode: '71806',
            department: 'Media Relations',
            startDate: '08/28/2022',
        },
        {
            firstName: 'Aiko',
            lastName: 'Meyers',
            dateOfBirth: '04/06/2023',
            street: '4596 Lacus. Ave',
            city: 'Gangneung',
            state: 'GE',
            zipCode: '35705',
            department: 'Legal Department',
            startDate: '08/22/2021',
        },
        {
            firstName: 'Paki',
            lastName: 'Valenzuela',
            dateOfBirth: '07/26/2022',
            street: '861-2881 Quis St.',
            city: 'Bangor',
            state: 'FL',
            zipCode: '97659',
            department: 'Customer Service',
            startDate: '02/03/2022',
        },
        {
            firstName: 'Alexandra',
            lastName: 'Ferrell',
            dateOfBirth: '10/11/2021',
            street: '837-2673 Lobortis. St.',
            city: 'Dublin',
            state: 'ID',
            zipCode: '22776',
            department: 'Advertising',
            startDate: '03/10/2022',
        },
        {
            firstName: 'Barrett',
            lastName: 'Dickson',
            dateOfBirth: '07/25/2021',
            street: '197-5336 Ac Road',
            city: 'Invercargill',
            state: 'KA',
            zipCode: '35611',
            department: 'Legal Department',
            startDate: '02/14/2023',
        },
        {
            firstName: 'Garth',
            lastName: 'Ford',
            dateOfBirth: '04/24/2023',
            street: '444-2352 Risus. Av.',
            city: 'Turbo',
            state: 'AR',
            zipCode: '35916',
            department: 'Accounting',
            startDate: '07/15/2022',
        },
        {
            firstName: 'Ronan',
            lastName: 'Blair',
            dateOfBirth: '04/29/2021',
            street: '3643 Varius Avenue',
            city: 'Casper',
            state: 'IN',
            zipCode: '17360',
            department: 'Human Resources',
            startDate: '01/05/2022',
        },
        {
            firstName: 'Coby',
            lastName: 'Snyder',
            dateOfBirth: '02/20/2023',
            street: 'Ap #577-5064 Placerat. St.',
            city: 'Sydney',
            state: 'AL',
            zipCode: '26470',
            department: 'Sales and Marketing',
            startDate: '03/21/2023',
        },
        {
            firstName: 'Denton',
            lastName: 'Williamson',
            dateOfBirth: '01/21/2023',
            street: 'Ap #287-8034 Non, Rd.',
            city: 'Xinjiang',
            state: 'MI',
            zipCode: '79348',
            department: 'Customer Relations',
            startDate: '05/10/2021',
        },
        {
            firstName: 'Halla',
            lastName: 'Wagner',
            dateOfBirth: '01/14/2022',
            street: '1867 Nulla Avenue',
            city: 'Niort',
            state: 'MAR',
            zipCode: '99781',
            department: 'Asset Management',
            startDate: '01/11/2023',
        },
        {
            firstName: 'Quinn',
            lastName: 'Alford',
            dateOfBirth: '10/05/2022',
            street: 'Ap #642-2360 Erat Road',
            city: 'New Quay',
            state: 'MAR',
            zipCode: '35182',
            department: 'Media Relations',
            startDate: '10/04/2021',
        },
        {
            firstName: 'Belle',
            lastName: 'Nichols',
            dateOfBirth: '04/21/2022',
            street: '3356 Elit, Ave',
            city: 'Acquedolci',
            state: 'ARK',
            zipCode: '86586',
            department: 'Asset Management',
            startDate: '04/21/2022',
        },
        {
            firstName: 'Robin',
            lastName: 'Pennington',
            dateOfBirth: '10/05/2022',
            street: '6894 Non St.',
            city: 'İzmit',
            state: 'OKL',
            zipCode: '87573',
            department: 'Public Relations',
            startDate: '09/16/2022',
        },
        {
            firstName: 'Glenna',
            lastName: 'Coleman',
            dateOfBirth: '12/25/2022',
            street: '560 Vulputate, Street',
            city: 'Riosucio',
            state: 'COL',
            zipCode: '76544',
            department: 'Legal Department',
            startDate: '07/03/2022',
        },
        {
            firstName: 'Dacey',
            lastName: 'French',
            dateOfBirth: '12/13/2021',
            street: '5575 Sociis Av.',
            city: 'Shanxi',
            state: 'MASS',
            zipCode: '96415',
            department: 'Legal Department',
            startDate: '07/15/2022',
        },
        {
            firstName: 'Hannah',
            lastName: 'Wilson',
            dateOfBirth: '05/11/2021',
            street: 'Ap #511-8941 Bibendum Rd.',
            city: 'Carmen de Bolivar',
            state: 'MI',
            zipCode: '99611',
            department: 'Media Relations',
            startDate: '10/05/2022',
        },
        {
            firstName: 'Whitney',
            lastName: 'Patel',
            dateOfBirth: '01/11/2022',
            street: 'Ap #825-3267 Quis, Rd.',
            city: 'Digos',
            state: 'IO',
            zipCode: '86322',
            department: 'Human Resources',
            startDate: '02/05/2022',
        },
        {
            firstName: 'Audra',
            lastName: 'Le',
            dateOfBirth: '11/28/2022',
            street: '6598 Dignissim Rd.',
            city: 'Rawalpindi',
            state: 'TE',
            zipCode: '47406',
            department: 'Accounting',
            startDate: '05/20/2022',
        },
        {
            firstName: 'Kylie',
            lastName: 'William',
            dateOfBirth: '10/26/2021',
            street: '698-978 Turpis. Ave',
            city: 'Requínoa',
            state: 'NEB',
            zipCode: '91773',
            department: 'Customer Service',
            startDate: '01/17/2022',
        },
        {
            firstName: 'Randall',
            lastName: 'Campbell',
            dateOfBirth: '01/17/2022',
            street: 'Ap #933-7484 Dictum Road',
            city: 'Sart-Dames-Avelines',
            state: 'MI',
            zipCode: '60422',
            department: 'Customer Service',
            startDate: '10/30/2022',
        },
        {
            firstName: 'Phyllis',
            lastName: 'Ochoa',
            dateOfBirth: '11/02/2021',
            street: 'Ap #617-5869 Non, Rd.',
            city: 'Timon',
            state: 'MO',
            zipCode: '30117',
            department: 'Legal Department',
            startDate: '11/28/2021',
        },
        {
            firstName: 'Cassandra',
            lastName: 'Gates',
            dateOfBirth: '12/24/2022',
            street: '7723 Aliquam Road',
            city: "King William's Town",
            state: 'PEN',
            zipCode: '34417',
            department: 'Advertising',
            startDate: '07/09/2022',
        },
        {
            firstName: 'Rose',
            lastName: 'Mcconnell',
            dateOfBirth: '05/09/2022',
            street: '167-7885 Erat St.',
            city: 'Moscow',
            state: 'IO',
            zipCode: '51852',
            department: 'Sales and Marketing',
            startDate: '10/10/2022',
        },
        {
            firstName: 'Hunter',
            lastName: 'Bird',
            dateOfBirth: '01/05/2022',
            street: '174-6979 Adipiscing. Road',
            city: 'Heerhugowaard',
            state: 'GE',
            zipCode: '99681',
            department: 'Tech Support',
            startDate: '01/02/2023',
        },
        {
            firstName: 'Jael',
            lastName: 'Chaney',
            dateOfBirth: '03/06/2022',
            street: '739-4683 Sit Avenue',
            city: 'Tromsø',
            state: 'OR',
            zipCode: '71550',
            department: 'Public Relations',
            startDate: '04/04/2023',
        },
        {
            firstName: 'Dexter',
            lastName: 'Underwood',
            dateOfBirth: '09/10/2021',
            street: '813-529 Ultrices Road',
            city: 'Edremit',
            state: 'OR',
            zipCode: '85566',
            department: 'Sales and Marketing',
            startDate: '11/26/2021',
        },
        {
            firstName: 'Rana',
            lastName: 'Sexton',
            dateOfBirth: '01/11/2023',
            street: 'Ap #440-6489 Dolor. St.',
            city: 'Stargard Szczeciński',
            state: 'COL',
            zipCode: '68294',
            department: 'Customer Relations',
            startDate: '10/15/2022',
        },
        {
            firstName: 'Allen',
            lastName: 'Fitzpatrick',
            dateOfBirth: '02/08/2023',
            street: '568-3913 Non, Street',
            city: 'Şereflikoçhisar',
            state: 'Il',
            zipCode: '55272',
            department: 'Human Resources',
            startDate: '06/03/2022',
        },
        {
            firstName: 'Cooper',
            lastName: 'Irwin',
            dateOfBirth: '09/08/2022',
            street: 'P.O. Box 408, 6765 Pellentesque Street',
            city: 'Zhejiang',
            state: 'DEL',
            zipCode: '27559',
            department: 'Asset Management',
            startDate: '01/19/2023',
        },
        {
            firstName: 'Deborah',
            lastName: 'Moon',
            dateOfBirth: '02/15/2022',
            street: '738-1873 Dui, Street',
            city: 'Omsk',
            state: 'NEB',
            zipCode: '71823',
            department: 'Research and Development',
            startDate: '07/16/2022',
        },
        {
            firstName: 'Ila',
            lastName: 'Hurst',
            dateOfBirth: '01/12/2023',
            street: '746-622 Ipsum Avenue',
            city: 'Colwood',
            state: 'OH',
            zipCode: '51746',
            department: 'Media Relations',
            startDate: '07/17/2021',
        },
        {
            firstName: 'India',
            lastName: 'Haney',
            dateOfBirth: '03/21/2022',
            street: 'P.O. Box 831, 9003 Magna. Ave',
            city: 'Biała Podlaska',
            state: 'WA',
            zipCode: '86625',
            department: 'Finances',
            startDate: '01/09/2022',
        },
        {
            firstName: 'Yasir',
            lastName: 'Compton',
            dateOfBirth: '01/15/2022',
            street: 'Ap #701-3621 Suspendisse St.',
            city: 'Innsbruck',
            state: 'TE',
            zipCode: '24202',
            department: 'Asset Management',
            startDate: '08/13/2022',
        },
        {
            firstName: 'Declan',
            lastName: 'Barber',
            dateOfBirth: '09/29/2021',
            street: 'P.O. Box 732, 989 Consectetuer Ave',
            city: 'Missoula',
            state: 'AL',
            zipCode: '72684',
            department: 'Quality Assurance',
            startDate: '12/16/2021',
        },
        {
            firstName: 'Dorothy',
            lastName: 'Bartlett',
            dateOfBirth: '08/11/2021',
            street: 'Ap #124-1285 Accumsan Street',
            city: 'Moulins',
            state: 'MI',
            zipCode: '14479',
            department: 'Payroll',
            startDate: '01/31/2023',
        },
        {
            firstName: 'Jerome',
            lastName: 'Grimes',
            dateOfBirth: '09/05/2021',
            street: '698-2901 Nunc Street',
            city: 'Plato',
            state: 'MIN',
            zipCode: '86976',
            department: 'Legal Department',
            startDate: '01/03/2023',
        },
        {
            firstName: 'Amal',
            lastName: 'Patel',
            dateOfBirth: '05/08/2021',
            street: '969-493 Mollis Rd.',
            city: 'Delitzsch',
            state: 'TE',
            zipCode: '45487',
            department: 'Customer Service',
            startDate: '05/02/2021',
        },
        {
            firstName: 'Pearl',
            lastName: 'Hudson',
            dateOfBirth: '08/17/2021',
            street: '717-2520 Phasellus Rd.',
            city: 'Hubei',
            state: 'MAI',
            zipCode: '64311',
            department: 'Public Relations',
            startDate: '02/23/2023',
        },
        {
            firstName: 'Louis',
            lastName: 'Stevens',
            dateOfBirth: '11/24/2022',
            street: 'Ap #484-3836 Placerat, Ave',
            city: 'Iksan',
            state: 'IN',
            zipCode: '78458',
            department: 'Customer Service',
            startDate: '04/06/2023',
        },
        {
            firstName: 'Tana',
            lastName: 'Chambers',
            dateOfBirth: '03/08/2023',
            street: 'P.O. Box 557, 3942 Tempor Rd.',
            city: 'Lang',
            state: 'TEN',
            zipCode: '37279',
            department: 'Payroll',
            startDate: '04/27/2021',
        },
        {
            firstName: 'Nita',
            lastName: 'Blevins',
            dateOfBirth: '12/07/2021',
            street: '831-1133 Consequat Avenue',
            city: 'Heilbronn',
            state: 'MI',
            zipCode: '56568',
            department: 'Sales and Marketing',
            startDate: '04/11/2022',
        },
        {
            firstName: 'Ivy',
            lastName: 'Hopkins',
            dateOfBirth: '01/11/2023',
            street: 'P.O. Box 656, 164 Amet Ave',
            city: 'San Nicolás',
            state: 'VI',
            zipCode: '56042',
            department: 'Quality Assurance',
            startDate: '05/17/2021',
        },
        {
            firstName: 'Griffith',
            lastName: 'Moore',
            dateOfBirth: '06/25/2021',
            street: 'P.O. Box 294, 6069 Quisque Rd.',
            city: 'Tulsa',
            state: 'WYO',
            zipCode: '25622',
            department: 'Media Relations',
            startDate: '02/01/2022',
        },
        {
            firstName: 'Kristen',
            lastName: 'Emerson',
            dateOfBirth: '10/09/2022',
            street: '433-3983 Ut Road',
            city: 'Boryeong',
            state: 'MISS',
            zipCode: '86773',
            department: 'Media Relations',
            startDate: '05/03/2022',
        },
        {
            firstName: 'Florence',
            lastName: 'Hahn',
            dateOfBirth: '10/20/2022',
            street: 'P.O. Box 396, 1688 Elit Avenue',
            city: 'Stade',
            state: 'MI',
            zipCode: '87269',
            department: 'Quality Assurance',
            startDate: '11/03/2021',
        },
        {
            firstName: 'Upton',
            lastName: 'Navarro',
            dateOfBirth: '12/27/2022',
            street: 'Ap #762-2754 Augue Rd.',
            city: 'Secunda',
            state: 'VER',
            zipCode: '94527',
            department: 'Asset Management',
            startDate: '06/23/2021',
        },
        {
            firstName: 'Ella',
            lastName: 'Hill',
            dateOfBirth: '10/17/2021',
            street: '7482 Volutpat. St.',
            city: 'Deventer',
            state: 'CAL',
            zipCode: '27575',
            department: 'Tech Support',
            startDate: '03/13/2022',
        },
        {
            firstName: 'Caldwell',
            lastName: 'Norton',
            dateOfBirth: '12/06/2021',
            street: 'P.O. Box 222, 2287 Eget St.',
            city: 'Zhejiang',
            state: 'MASS',
            zipCode: '18568',
            department: 'Public Relations',
            startDate: '09/30/2022',
        },
        {
            firstName: 'Moses',
            lastName: 'Thornton',
            dateOfBirth: '12/10/2021',
            street: 'Ap #490-7086 Tristique Rd.',
            city: 'Moen',
            state: 'MASS',
            zipCode: '46594',
            department: 'Sales and Marketing',
            startDate: '04/01/2023',
        },
        {
            firstName: 'Gage',
            lastName: 'Stein',
            dateOfBirth: '03/31/2023',
            street: '3834 Nullam Av.',
            city: 'Milestone',
            state: 'Il',
            zipCode: '38562',
            department: 'Media Relations',
            startDate: '12/17/2022',
        },
        {
            firstName: 'Zelda',
            lastName: 'Bridges',
            dateOfBirth: '11/05/2021',
            street: 'P.O. Box 716, 4430 Eget, Street',
            city: 'Barranca',
            state: 'PEN',
            zipCode: '49558',
            department: 'Tech Support',
            startDate: '03/30/2022',
        },
        {
            firstName: 'Steven',
            lastName: 'Bond',
            dateOfBirth: '09/02/2022',
            street: 'P.O. Box 506, 4516 Commodo Rd.',
            city: 'Palmira',
            state: 'AL',
            zipCode: '51831',
            department: 'Asset Management',
            startDate: '09/01/2022',
        },
        {
            firstName: 'Jessamine',
            lastName: 'Daniel',
            dateOfBirth: '03/08/2023',
            street: 'Ap #696-2582 Mauris St.',
            city: 'Kano',
            state: 'PEN',
            zipCode: '71103',
            department: 'Research and Development',
            startDate: '04/08/2023',
        },
        {
            firstName: 'Gareth',
            lastName: 'Spencer',
            dateOfBirth: '06/24/2022',
            street: '772-5486 Nam Ave',
            city: 'Nizip',
            state: 'KA',
            zipCode: '72822',
            department: 'Customer Relations',
            startDate: '09/12/2021',
        },
        {
            firstName: 'Emmanuel',
            lastName: 'Armstrong',
            dateOfBirth: '12/28/2021',
            street: '8892 Ut Rd.',
            city: 'Punggol',
            state: 'DEL',
            zipCode: '44858',
            department: 'Payroll',
            startDate: '07/09/2022',
        },
        {
            firstName: 'Carter',
            lastName: 'Bell',
            dateOfBirth: '07/25/2021',
            street: 'P.O. Box 514, 1196 Tempus Avenue',
            city: 'Tuas',
            state: 'AL',
            zipCode: '62662',
            department: 'Advertising',
            startDate: '02/08/2022',
        },
        {
            firstName: 'Dane',
            lastName: 'Owen',
            dateOfBirth: '06/05/2022',
            street: '1179 Quis Avenue',
            city: 'Quimbaya',
            state: 'COL',
            zipCode: '71595',
            department: 'Public Relations',
            startDate: '12/13/2021',
        },
        {
            firstName: 'Yoko',
            lastName: 'Clay',
            dateOfBirth: '05/07/2021',
            street: 'Ap #150-7288 Rhoncus. Road',
            city: 'Cajazeiras',
            state: 'UT',
            zipCode: '74845',
            department: 'Payroll',
            startDate: '02/13/2022',
        },
        {
            firstName: 'Addison',
            lastName: 'Dixon',
            dateOfBirth: '04/12/2023',
            street: '812-6688 Egestas. Road',
            city: 'Sengkang',
            state: 'WA',
            zipCode: '51182',
            department: 'Customer Service',
            startDate: '12/17/2021',
        },
        {
            firstName: 'Kerry',
            lastName: 'Mccarty',
            dateOfBirth: '06/29/2022',
            street: 'Ap #495-8515 Sed, Av.',
            city: 'Almere',
            state: 'NEV',
            zipCode: '85517',
            department: 'Human Resources',
            startDate: '03/28/2023',
        },
        {
            firstName: 'Reece',
            lastName: 'Potter',
            dateOfBirth: '11/15/2021',
            street: 'P.O. Box 589, 5702 Cras Road',
            city: 'De Haan',
            state: 'MO',
            zipCode: '71579',
            department: 'Human Resources',
            startDate: '12/11/2021',
        },
        {
            firstName: 'Jerome',
            lastName: 'Chandler',
            dateOfBirth: '06/18/2021',
            street: '654-9982 Duis Street',
            city: 'New Plymouth',
            state: 'WYO',
            zipCode: '41722',
            department: 'Legal Department',
            startDate: '07/05/2022',
        },
        {
            firstName: 'August',
            lastName: 'Berg',
            dateOfBirth: '12/24/2021',
            street: 'P.O. Box 243, 3098 Sollicitudin Road',
            city: 'Jaén',
            state: 'ARK',
            zipCode: '57581',
            department: 'Quality Assurance',
            startDate: '04/16/2023',
        },
        {
            firstName: 'Iliana',
            lastName: 'Flynn',
            dateOfBirth: '03/06/2022',
            street: '4719 Nullam Rd.',
            city: 'Thalassery',
            state: 'FL',
            zipCode: '91681',
            department: 'Legal Department',
            startDate: '05/05/2021',
        },
        {
            firstName: 'Hammett',
            lastName: 'Puckett',
            dateOfBirth: '01/08/2023',
            street: 'Ap #538-4367 Dolor St.',
            city: 'Bắc Kạn',
            state: 'CAL',
            zipCode: '35915',
            department: 'Public Relations',
            startDate: '03/22/2023',
        },
        {
            firstName: 'Kadeem',
            lastName: 'Ayala',
            dateOfBirth: '09/28/2022',
            street: '101-3752 Sem. Rd.',
            city: 'Nairn',
            state: 'TE',
            zipCode: '71718',
            department: 'Finances',
            startDate: '07/29/2021',
        },
        {
            firstName: 'Whoopi',
            lastName: 'Tillman',
            dateOfBirth: '07/08/2022',
            street: 'Ap #900-6887 Senectus Rd.',
            city: 'Konin',
            state: 'VI',
            zipCode: '75427',
            department: 'Asset Management',
            startDate: '07/11/2022',
        },
        {
            firstName: 'Samuel',
            lastName: 'Chen',
            dateOfBirth: '11/03/2021',
            street: 'P.O. Box 603, 5095 Semper Rd.',
            city: 'Skardu',
            state: 'MAR',
            zipCode: '35677',
            department: 'Media Relations',
            startDate: '09/12/2022',
        },
        {
            firstName: 'Mallory',
            lastName: 'Graves',
            dateOfBirth: '08/29/2022',
            street: '8143 Aliquam, Avenue',
            city: 'Guizhou',
            state: 'ID',
            zipCode: '73852',
            department: 'Legal Department',
            startDate: '04/03/2022',
        },
        {
            firstName: 'Kamal',
            lastName: 'Beck',
            dateOfBirth: '08/20/2022',
            street: '320-1237 Ante St.',
            city: 'Manavgat',
            state: 'KT',
            zipCode: '25010',
            department: 'Customer Relations',
            startDate: '10/04/2022',
        },
        {
            firstName: 'Lacy',
            lastName: 'Santana',
            dateOfBirth: '05/13/2021',
            street: 'Ap #944-6028 Penatibus Rd.',
            city: 'Wonju',
            state: 'ID',
            zipCode: '86196',
            department: 'Accounting',
            startDate: '06/04/2021',
        },
        {
            firstName: 'Sawyer',
            lastName: 'Pate',
            dateOfBirth: '02/21/2023',
            street: '8470 Tempus St.',
            city: 'Dortmund',
            state: 'NEB',
            zipCode: '73227',
            department: 'Accounting',
            startDate: '08/31/2022',
        },
        {
            firstName: 'Drake',
            lastName: 'Klein',
            dateOfBirth: '02/26/2022',
            street: '105-4456 Pede. Rd.',
            city: 'Tczew',
            state: 'AL',
            zipCode: '88046',
            department: 'Asset Management',
            startDate: '01/13/2023',
        },
        {
            firstName: 'Brody',
            lastName: 'Pratt',
            dateOfBirth: '06/06/2022',
            street: '425-3451 Malesuada St.',
            city: 'Geelong',
            state: 'WISC',
            zipCode: '20458',
            department: 'Advertising',
            startDate: '08/01/2022',
        },
        {
            firstName: 'Alma',
            lastName: 'Owen',
            dateOfBirth: '04/28/2021',
            street: '1599 Nunc Road',
            city: 'Shanxi',
            state: 'NEV',
            zipCode: '93023',
            department: 'Customer Service',
            startDate: '05/21/2021',
        },
        {
            firstName: 'Armand',
            lastName: 'Howell',
            dateOfBirth: '01/14/2023',
            street: '572-5938 Primis Rd.',
            city: 'Padang Panjang',
            state: 'UT',
            zipCode: '82507',
            department: 'Research and Development',
            startDate: '09/13/2022',
        },
        {
            firstName: 'Arthur',
            lastName: 'Yang',
            dateOfBirth: '03/18/2022',
            street: '817-8887 Nullam St.',
            city: 'Nurdağı',
            state: 'PEN',
            zipCode: '65541',
            department: 'Media Relations',
            startDate: '04/26/2022',
        },
        {
            firstName: 'Daquan',
            lastName: 'Holland',
            dateOfBirth: '09/25/2021',
            street: 'P.O. Box 524, 9366 Vivamus Av.',
            city: 'Cuglieri',
            state: 'AL',
            zipCode: '32437',
            department: 'Human Resources',
            startDate: '05/01/2021',
        },
        {
            firstName: 'Hadley',
            lastName: 'Mclean',
            dateOfBirth: '07/26/2021',
            street: 'Ap #423-3302 Amet, Av.',
            city: 'Thabazimbi',
            state: 'TE',
            zipCode: '95355',
            department: 'Customer Relations',
            startDate: '10/21/2021',
        },
        {
            firstName: 'Gemma',
            lastName: 'Mclaughlin',
            dateOfBirth: '10/21/2022',
            street: 'P.O. Box 738, 9903 Nec, Road',
            city: 'Emalahleni',
            state: 'VER',
            zipCode: '65085',
            department: 'Tech Support',
            startDate: '06/17/2021',
        },
        {
            firstName: 'Tarik',
            lastName: 'Mccarty',
            dateOfBirth: '10/23/2021',
            street: '279-2826 Quisque Av.',
            city: 'Ryazan',
            state: 'TE',
            zipCode: '93506',
            department: 'Tech Support',
            startDate: '12/31/2021',
        },
        {
            firstName: 'Urielle',
            lastName: 'Nolan',
            dateOfBirth: '03/15/2022',
            street: '724-9011 Erat Avenue',
            city: 'Nagaon',
            state: 'MISS',
            zipCode: '45528',
            department: 'Sales and Marketing',
            startDate: '01/22/2022',
        },
        {
            firstName: 'Bruce',
            lastName: 'Vinson',
            dateOfBirth: '07/22/2021',
            street: 'P.O. Box 289, 6891 Luctus, Street',
            city: 'Huaraz',
            state: 'ARK',
            zipCode: '58653',
            department: 'Human Resources',
            startDate: '11/22/2022',
        },
        {
            firstName: 'Clare',
            lastName: 'Simmons',
            dateOfBirth: '02/12/2022',
            street: '2279 Adipiscing St.',
            city: 'Motueka',
            state: 'WISC',
            zipCode: '55282',
            department: 'Public Relations',
            startDate: '06/11/2022',
        },
        {
            firstName: 'Charity',
            lastName: 'Melendez',
            dateOfBirth: '04/20/2023',
            street: 'Ap #189-5530 Euismod Rd.',
            city: 'Donosti',
            state: 'DEL',
            zipCode: '46229',
            department: 'Public Relations',
            startDate: '07/08/2021',
        },
        {
            firstName: 'TaShya',
            lastName: 'Patrick',
            dateOfBirth: '06/08/2021',
            street: 'Ap #226-4586 Egestas Rd.',
            city: 'Odda',
            state: 'WA',
            zipCode: '60160',
            department: 'Public Relations',
            startDate: '09/27/2021',
        },
        {
            firstName: 'Odessa',
            lastName: 'Lang',
            dateOfBirth: '01/16/2023',
            street: '884-8977 Tempus Ave',
            city: 'Isnes',
            state: 'TEN',
            zipCode: '57078',
            department: 'Accounting',
            startDate: '06/23/2022',
        },
        {
            firstName: 'Kieran',
            lastName: 'Owens',
            dateOfBirth: '01/31/2022',
            street: 'Ap #582-8204 Massa. Rd.',
            city: 'Tanjay',
            state: 'AL',
            zipCode: '64151',
            department: 'Sales and Marketing',
            startDate: '03/25/2023',
        },
        {
            firstName: 'Arthur',
            lastName: 'Reid',
            dateOfBirth: '10/07/2021',
            street: 'Ap #671-4282 Ornare, St.',
            city: 'North Waziristan',
            state: 'MO',
            zipCode: '91374',
            department: 'Media Relations',
            startDate: '05/22/2022',
        },
        {
            firstName: 'Brandon',
            lastName: 'Torres',
            dateOfBirth: '03/29/2023',
            street: 'Ap #675-4338 Malesuada Av.',
            city: 'Yurimaguas',
            state: 'AR',
            zipCode: '42659',
            department: 'Media Relations',
            startDate: '05/06/2022',
        },
        {
            firstName: 'Pamela',
            lastName: 'Waters',
            dateOfBirth: '07/27/2021',
            street: '506-9212 Magna, Street',
            city: 'Lauterach',
            state: 'HAW',
            zipCode: '50115',
            department: 'Tech Support',
            startDate: '06/11/2022',
        },
        {
            firstName: 'Iona',
            lastName: 'Buckner',
            dateOfBirth: '09/10/2022',
            street: '3199 Quam Av.',
            city: 'Rzeszów',
            state: 'HAW',
            zipCode: '28027',
            department: 'Asset Management',
            startDate: '08/23/2022',
        },
        {
            firstName: 'August',
            lastName: 'Simpson',
            dateOfBirth: '07/31/2021',
            street: '349-9526 Non Rd.',
            city: 'Monclova',
            state: 'AL',
            zipCode: '86732',
            department: 'Media Relations',
            startDate: '11/26/2022',
        },
        {
            firstName: 'Christen',
            lastName: 'Sargent',
            dateOfBirth: '06/13/2021',
            street: '787-7624 Per Av.',
            city: 'Puno',
            state: 'WA',
            zipCode: '93351',
            department: 'Payroll',
            startDate: '09/05/2021',
        },
        {
            firstName: 'Rinah',
            lastName: 'Hopkins',
            dateOfBirth: '06/04/2022',
            street: '9541 Praesent St.',
            city: 'Matamoros',
            state: 'WYO',
            zipCode: '41381',
            department: 'Customer Relations',
            startDate: '08/06/2021',
        },
        {
            firstName: 'Anastasia',
            lastName: 'Blair',
            dateOfBirth: '07/31/2022',
            street: '603-632 At, Rd.',
            city: 'Liaoning',
            state: 'AR',
            zipCode: '36959',
            department: 'Quality Assurance',
            startDate: '08/19/2022',
        },
    ];
    employeesData.forEach(employee => {
        employees.push(employee);
    })
    localStorage.setItem('employees', JSON.stringify(employees));
    $('#confirmation').modal();
}

const states = [
    {
        "name": "Alabama",
        "abbreviation": "AL"
    },
    {
        "name": "Alaska",
        "abbreviation": "AK"
    },
    {
        "name": "American Samoa",
        "abbreviation": "AS"
    },
    {
        "name": "Arizona",
        "abbreviation": "AZ"
    },
    {
        "name": "Arkansas",
        "abbreviation": "AR"
    },
    {
        "name": "California",
        "abbreviation": "CA"
    },
    {
        "name": "Colorado",
        "abbreviation": "CO"
    },
    {
        "name": "Connecticut",
        "abbreviation": "CT"
    },
    {
        "name": "Delaware",
        "abbreviation": "DE"
    },
    {
        "name": "District Of Columbia",
        "abbreviation": "DC"
    },
    {
        "name": "Federated States Of Micronesia",
        "abbreviation": "FM"
    },
    {
        "name": "Florida",
        "abbreviation": "FL"
    },
    {
        "name": "Georgia",
        "abbreviation": "GA"
    },
    {
        "name": "Guam",
        "abbreviation": "GU"
    },
    {
        "name": "Hawaii",
        "abbreviation": "HI"
    },
    {
        "name": "Idaho",
        "abbreviation": "ID"
    },
    {
        "name": "Illinois",
        "abbreviation": "IL"
    },
    {
        "name": "Indiana",
        "abbreviation": "IN"
    },
    {
        "name": "Iowa",
        "abbreviation": "IA"
    },
    {
        "name": "Kansas",
        "abbreviation": "KS"
    },
    {
        "name": "Kentucky",
        "abbreviation": "KY"
    },
    {
        "name": "Louisiana",
        "abbreviation": "LA"
    },
    {
        "name": "Maine",
        "abbreviation": "ME"
    },
    {
        "name": "Marshall Islands",
        "abbreviation": "MH"
    },
    {
        "name": "Maryland",
        "abbreviation": "MD"
    },
    {
        "name": "Massachusetts",
        "abbreviation": "MA"
    },
    {
        "name": "Michigan",
        "abbreviation": "MI"
    },
    {
        "name": "Minnesota",
        "abbreviation": "MN"
    },
    {
        "name": "Mississippi",
        "abbreviation": "MS"
    },
    {
        "name": "Missouri",
        "abbreviation": "MO"
    },
    {
        "name": "Montana",
        "abbreviation": "MT"
    },
    {
        "name": "Nebraska",
        "abbreviation": "NE"
    },
    {
        "name": "Nevada",
        "abbreviation": "NV"
    },
    {
        "name": "New Hampshire",
        "abbreviation": "NH"
    },
    {
        "name": "New Jersey",
        "abbreviation": "NJ"
    },
    {
        "name": "New Mexico",
        "abbreviation": "NM"
    },
    {
        "name": "New York",
        "abbreviation": "NY"
    },
    {
        "name": "North Carolina",
        "abbreviation": "NC"
    },
    {
        "name": "North Dakota",
        "abbreviation": "ND"
    },
    {
        "name": "Northern Mariana Islands",
        "abbreviation": "MP"
    },
    {
        "name": "Ohio",
        "abbreviation": "OH"
    },
    {
        "name": "Oklahoma",
        "abbreviation": "OK"
    },
    {
        "name": "Oregon",
        "abbreviation": "OR"
    },
    {
        "name": "Palau",
        "abbreviation": "PW"
    },
    {
        "name": "Pennsylvania",
        "abbreviation": "PA"
    },
    {
        "name": "Puerto Rico",
        "abbreviation": "PR"
    },
    {
        "name": "Rhode Island",
        "abbreviation": "RI"
    },
    {
        "name": "South Carolina",
        "abbreviation": "SC"
    },
    {
        "name": "South Dakota",
        "abbreviation": "SD"
    },
    {
        "name": "Tennessee",
        "abbreviation": "TN"
    },
    {
        "name": "Texas",
        "abbreviation": "TX"
    },
    {
        "name": "Utah",
        "abbreviation": "UT"
    },
    {
        "name": "Vermont",
        "abbreviation": "VT"
    },
    {
        "name": "Virgin Islands",
        "abbreviation": "VI"
    },
    {
        "name": "Virginia",
        "abbreviation": "VA"
    },
    {
        "name": "Washington",
        "abbreviation": "WA"
    },
    {
        "name": "West Virginia",
        "abbreviation": "WV"
    },
    {
        "name": "Wisconsin",
        "abbreviation": "WI"
    },
    {
        "name": "Wyoming",
        "abbreviation": "WY"
    }
];